export const ESMA_UL_HUSNA = [
  { id: 1, nameAr: 'الله', nameTr: 'Allah', meaning: 'Eşi benzeri olmayan, bütün noksan sıfatlardan münezzeh tek yüce ilah.', meaningEn: 'The One, the All-Mighty, the Only God.' },
  { id: 2, nameAr: 'الرَّحْمَنِ', nameTr: 'Er-Rahmân', meaning: 'Dünyada bütün mahlukata merhamet eden, şefkat gösteren, ihsan eden.', meaningEn: 'The Most Gracious.' },
  { id: 3, nameAr: 'الرَّحِيمِ', nameTr: 'Er-Rahîm', meaning: 'Ahirette, müminlere sonsuz ikram, lütuf ve ihsanda bulunan.', meaningEn: 'The Most Merciful.' },
  { id: 4, nameAr: 'الْمَلِكِ', nameTr: 'El-Melik', meaning: 'Mülkün, kâinatın sahibi, mülk ve saltanatı devamlı olan.', meaningEn: 'The Sovereign Lord.' },
  { id: 5, nameAr: 'الْقُدُّوسِ', nameTr: 'El-Kuddûs', meaning: 'Her noksanlıktan uzak ve her türlü takdîse layık olan.', meaningEn: 'The Holy One.' },
  { id: 6, nameAr: 'السَّلَامِ', nameTr: 'Es-Selâm', meaning: 'Her türlü tehlikelerden selamete çıkaran.', meaningEn: 'The Source of Peace.' },
  { id: 7, nameAr: 'الْمُؤْمِنِ', nameTr: 'El-Mü’min', meaning: 'Güven veren, emin kılan, koruyan.', meaningEn: 'The Guardian of Faith.' },
  { id: 8, nameAr: 'الْمُهَيْمِنِ', nameTr: 'El-Müheymin', meaning: 'Her şeyi görüp gözeten.', meaningEn: 'The Protector.' },
  { id: 9, nameAr: 'الْعَزِيزِ', nameTr: 'El-Azîz', meaning: 'İzzet sahibi, her şeye galip olan.', meaningEn: 'The Almighty.' },
  { id: 10, nameAr: 'الْجَبَّارِ', nameTr: 'El-Cebbâr', meaning: 'Azamet ve kudret sahibi. Dilediğini yapan ve yaptıran.', meaningEn: 'The Compeller.' },
  { id: 11, nameAr: 'الْمُتَكَبِّرِ', nameTr: 'El-Mütekebbir', meaning: 'Büyüklükte eşi, benzeri yok.', meaningEn: 'The Majestic.' },
  { id: 12, nameAr: 'الْخَالِقِ', nameTr: 'El-Hâlık', meaning: 'Yaratan, yoktan var eden.', meaningEn: 'The Creator.' },
  { id: 13, nameAr: 'الْبَارِئِ', nameTr: 'El-Bâri', meaning: 'Her şeyi kusursuz ve mütenasip yaratan.', meaningEn: 'The Maker of Order.' },
  { id: 14, nameAr: 'الْمُصَوِّرِ', nameTr: 'El-Musavvir', meaning: 'Mahlukata madde ve suret veren.', meaningEn: 'The Shaper of Beauty.' },
  { id: 15, nameAr: 'الْغَفَّارِ', nameTr: 'El-Gaffâr', meaning: 'Günahları örten ve çok mağfiret eden.', meaningEn: 'The Forgiving.' },
  { id: 16, nameAr: 'الْقَهَّارِ', nameTr: 'El-Kahhâr', meaning: 'Her şeye, her istendiğini yapacak surette galip ve hakim olan.', meaningEn: 'The Subduer.' },
  { id: 17, nameAr: 'الْوَهَّابِ', nameTr: 'El-Vehhâb', meaning: 'Karşılıksız hibeler veren, çok fazla ihsan eden.', meaningEn: 'The Giver of All.' },
  { id: 18, nameAr: 'الرَّزَّاقِ', nameTr: 'Er-Rezzâk', meaning: 'Bütün mahlukatın rızkını veren ve ihtiyacını karşılayan.', meaningEn: 'The Provider.' },
  { id: 19, nameAr: 'الْفَتَّاحِ', nameTr: 'El-Fettâh', meaning: 'Her türlü müşkülleri açan ve kolaylaştıran, darlıktan kurtaran.', meaningEn: 'The Opener.' },
  { id: 20, nameAr: 'الْعَلِيمِ', nameTr: 'El-Alîm', meaning: 'Gizli açık, geçmiş, gelecek, her şeyi en ince detaylarına kadar bilen.', meaningEn: 'The Knower of All.' },
  { id: 21, nameAr: 'الْقَابِضِ', nameTr: 'El-Kâbıd', meaning: 'Dilediğine darlik veren, sıkan, daraltan.', meaningEn: 'The Constrictor.' },
  { id: 22, nameAr: 'الْبَاسِطِ', nameTr: 'El-Bâsıt', meaning: 'Dilediğine bolluk veren, açan, genişleten.', meaningEn: 'The Reliever.' },
  { id: 23, nameAr: 'الْخَافِضِ', nameTr: 'El-Hâfıd', meaning: 'Dereceleri alçaltan.', meaningEn: 'The Abaser.' },
  { id: 24, nameAr: 'الرَّافِعِ', nameTr: 'Er-Râfi', meaning: 'Şeref verip yükselten.', meaningEn: 'The Exalter.' },
  { id: 25, nameAr: 'الْمُعِزِّ', nameTr: 'El-Muiz', meaning: 'Dilediğini aziz eden, izzet veren.', meaningEn: 'The Bestower of Honors.' },
  { id: 26, nameAr: 'الْمُذِلِّ', nameTr: 'El-Müzil', meaning: 'Dilediğini zillete düşüren.', meaningEn: 'The Humiliator.' },
  { id: 27, nameAr: 'السَّمِيعِ', nameTr: 'Es-Semî', meaning: 'Her şeyi en iyi işiten.', meaningEn: 'The Hearer of All.' },
  { id: 28, nameAr: 'الْبَصِيرِ', nameTr: 'El-Basîr', meaning: 'Gizli açık, her şeyi en iyi gören.', meaningEn: 'The Seer of All.' },
  { id: 29, nameAr: 'الْحَكَمِ', nameTr: 'El-Hakem', meaning: 'Mutlak hakim, hakkı batıldan ayıran. Hikmetle hükmeden.', meaningEn: 'The Judge.' },
  { id: 30, nameAr: 'الْعَدْلِ', nameTr: 'El-Adl', meaning: 'Mutlak adil, çok adaletli.', meaningEn: 'The Just.' },
  { id: 31, nameAr: 'اللَّطِيفِ', nameTr: 'El-Latîf', meaning: 'Lütuf ve ihsan sahibi olan. Bütün incelikleri bilen.', meaningEn: 'The Subtle One.' },
  { id: 32, nameAr: 'الْخَبِيرِ', nameTr: 'El-Habîr', meaning: 'Olmuş olacak her şeyden haberdar.', meaningEn: 'The All-Aware.' },
  { id: 33, nameAr: 'الْحَلِيمِ', nameTr: 'El-Halîm', meaning: 'Cezada acele etmeyen, yumuşak davranan.', meaningEn: 'The Forbearing.' },
  { id: 34, nameAr: 'الْعَظِيمِ', nameTr: 'El-Azîm', meaning: 'Büyüklükte benzeri yok. Pek yüce.', meaningEn: 'The Magnificent.' },
  { id: 35, nameAr: 'الْغَفُورِ', nameTr: 'El-Gafûr', meaning: 'Affı, mağfireti bol.', meaningEn: 'The Forgiver and Hider of Faults.' },
  { id: 36, nameAr: 'الشَّكُورِ', nameTr: 'Eş-Şekûr', meaning: 'Az amele, çok sevap veren.', meaningEn: 'The Rewarder of Thankfulness.' },
  { id: 37, nameAr: 'الْعَلِيِّ', nameTr: 'El-Aliyy', meaning: 'Yüceler yücesi, çok yüce.', meaningEn: 'The Highest.' },
  { id: 38, nameAr: 'الْكَبِيرِ', nameTr: 'El-Kebîr', meaning: 'Büyüklükte eşi, benzeri yok.', meaningEn: 'The Greatest.' },
  { id: 39, nameAr: 'الْحَفِيظِ', nameTr: 'El-Hafîz', meaning: 'Her şeyi koruyucu olan.', meaningEn: 'The Preserver.' },
  { id: 40, nameAr: 'الْمُقِيتِ', nameTr: 'El-Mukît', meaning: 'Rızıkları yaratan.', meaningEn: 'The Nourisher.' },
  { id: 41, nameAr: 'الْحَسِيبِ', nameTr: 'El-Hasîb', meaning: 'Hesaba çeken, herkesin hayatı boyunca yaptıklarının hesabını bütün detayları ile bilen.', meaningEn: 'The Bringer of Judgment.' },
  { id: 42, nameAr: 'الْجَلِيلِ', nameTr: 'El-Celîl', meaning: 'Celal ve azamet sahibi olan.', meaningEn: 'The Majestic One.' },
  { id: 43, nameAr: 'الْكَرِيمِ', nameTr: 'El-Kerîm', meaning: 'Keremi, lütuf ve ihsanı bol, karşılıksız veren, çok ikram eden.', meaningEn: 'The Bountiful.' },
  { id: 44, nameAr: 'الرَّقِيبِ', nameTr: 'Er-Rakîb', meaning: 'Her varlığı, her işi her an gözeten. Bütün işleri murakabesi altında bulunduran.', meaningEn: 'The Watchful.' },
  { id: 45, nameAr: 'الْمُجِيبِ', nameTr: 'El-Mucîb', meaning: 'Duaları, istekleri kabul eden.', meaningEn: 'The Responder to Prayer.' },
  { id: 46, nameAr: 'الْوَاسِعِ', nameTr: 'El-Vâsi', meaning: 'Rahmet, kudret ve ilmi ile her şeyi ihata eden.', meaningEn: 'The All-Comprehending.' },
  { id: 47, nameAr: 'الْحَكِيمِ', nameTr: 'El-Hakîm', meaning: 'Her işi hikmetli, her şeyi hikmetle yaratan.', meaningEn: 'The Perfectly Wise.' },
  { id: 48, nameAr: 'الْوَدُودِ', nameTr: 'El-Vedûd', meaning: 'Kullarını en fazla seven, sevilmeye en layık olan.', meaningEn: 'The Loving One.' },
  { id: 49, nameAr: 'الْمَجِيدِ', nameTr: 'El-Mecîd', meaning: 'Her türlü noksandan münezzeh, şanı çok yüce olan.', meaningEn: 'The Most Glorious One.' },
  { id: 50, nameAr: 'الْبَاعِثِ', nameTr: 'El-Bâis', meaning: 'Ölüleri dirilten.', meaningEn: 'The Resurrector.' },
  { id: 51, nameAr: 'الشَّهِيدِ', nameTr: 'Eş-Şehîd', meaning: 'Her zaman her yerde hazır ve nazır olan.', meaningEn: 'The Witness.' },
  { id: 52, nameAr: 'الْحَقِّ', nameTr: 'El-Hakk', meaning: 'Varlığı hiç değişmeden duran. Var olan, hakkı ortaya çıkaran.', meaningEn: 'The Truth.' },
  { id: 53, nameAr: 'الْوَكِيلِ', nameTr: 'El-Vekîl', meaning: 'Kendisine tevekkül edenlerin işlerini en iyi neticeye ulaştıran.', meaningEn: 'The Trustee.' },
  { id: 54, nameAr: 'الْقَوِيِّ', nameTr: 'El-Kaviyy', meaning: 'Kudreti en üstün ve hiç azalmaz olan.', meaningEn: 'The Possessor of All Strength.' },
  { id: 55, nameAr: 'الْمَتِينِ', nameTr: 'El-Metîn', meaning: 'Kuvvet ve kudret menbaı, pek güçlü.', meaningEn: 'The Forceful One.' },
  { id: 56, nameAr: 'الْوَلِيِّ', nameTr: 'El-Veliyy', meaning: 'İnananların dostu, onları sevip yardım eden.', meaningEn: 'The Protecting Friend.' },
  { id: 57, nameAr: 'الْحَمِيدِ', nameTr: 'El-Hamîd', meaning: 'Her türlü hamd ve senaya layık olan.', meaningEn: 'The Praised One.' },
  { id: 58, nameAr: 'الْمُحْصِي', nameTr: 'El-Muhsî', meaning: 'Yarattığı ve yaratacağı bütün varlıkların sayısını bilen.', meaningEn: 'The Appraiser.' },
  { id: 59, nameAr: 'الْمُبْدِئِ', nameTr: 'El-Mübdî', meaning: 'Maddesiz, örneksiz yaratan.', meaningEn: 'The Originator.' },
  { id: 60, nameAr: 'الْمُعِيدِ', nameTr: 'El-Muîd', meaning: 'Yarattıklarını yok edip, sonra tekrar diriltecek olan.', meaningEn: 'The Restorer.' },
  { id: 61, nameAr: 'الْمُحْيِي', nameTr: 'El-Muhyî', meaning: 'İhya eden, dirilten, can veren.', meaningEn: 'The Giver of Life.' },
  { id: 62, nameAr: 'الْمُمِيتِ', nameTr: 'El-Mümît', meaning: 'Her canlıya ölümü tattıran.', meaningEn: 'The Taker of Life.' },
  { id: 63, nameAr: 'الْحَيِّ', nameTr: 'El-Hayy', meaning: 'Ezeli ve ebedi hayata sahip olan.', meaningEn: 'The Ever Living One.' },
  { id: 64, nameAr: 'الْقَيُّومِ', nameTr: 'El-Kayyûm', meaning: 'Varlıkları diri tutan, zatı ile kaim olan.', meaningEn: 'The Self-Existing One.' },
  { id: 65, nameAr: 'الْوَاجِدِ', nameTr: 'El-Vâcid', meaning: 'Kendisinden hiçbir şey gizli olmayan, istediğini, istediği vakit bulan.', meaningEn: 'The Finder.' },
  { id: 66, nameAr: 'الْمَاجِدِ', nameTr: 'El-Mâcid', meaning: 'Kadri ve şanı büyük, keremi, ihsanı bol olan.', meaningEn: 'The Noble.' },
  { id: 67, nameAr: 'الْوَاحِدِ', nameTr: 'El-Vâhid', meaning: 'Zat, sıfat ve fiillerinde benzeri ve ortağı olmayan, tek olan.', meaningEn: 'The Unique.' },
  { id: 68, nameAr: 'الصَّمَدِ', nameTr: 'Es-Samed', meaning: 'Hiçbir şeye ihtiyacı olmayan, herkesin muhtaç olduğu.', meaningEn: 'The Eternal.' },
  { id: 69, nameAr: 'الْقَادِرِ', nameTr: 'El-Kâdir', meaning: 'Dilediğini dilediği gibi yaratmaya muktedir olan.', meaningEn: 'The Able.' },
  { id: 70, nameAr: 'الْمُقْتَدِرِ', nameTr: 'El-Muktedir', meaning: 'Dilediği gibi tasarruf eden, her şeyi kolayca yaratan kudret sahibi.', meaningEn: 'The Powerful.' },
  { id: 71, nameAr: 'الْمُقَدِّمِ', nameTr: 'El-Mukaddim', meaning: 'Dilediğini, öne alan, yükselten.', meaningEn: 'The Expediter.' },
  { id: 72, nameAr: 'الْمُؤَخِّرِ', nameTr: 'El-Muahhir', meaning: 'Dilediğini sona alan, erteleyen, alçaltan.', meaningEn: 'The Delayer.' },
  { id: 73, nameAr: 'الْأَوَّلِ', nameTr: 'El-Evvel', meaning: 'Ezeli olan, varlığının başlangıcı olmayan.', meaningEn: 'The First.' },
  { id: 74, nameAr: 'الْآخِرِ', nameTr: 'El-Âhir', meaning: 'Ebedi olan, varlığının sonu olmayan.', meaningEn: 'The Last.' },
  { id: 75, nameAr: 'الظَّاهِرِ', nameTr: 'Ez-Zâhir', meaning: 'Yarattıkları ile varlığı açık, aşikâr olan, kati delillerle bilinen.', meaningEn: 'The Manifest.' },
  { id: 76, nameAr: 'الْبَاطِنِ', nameTr: 'El-Bâtın', meaning: 'Aklın tasavvurundan gizli olan.', meaningEn: 'The Hidden.' },
  { id: 77, nameAr: 'الْوَالِي', nameTr: 'El-Vâlî', meaning: 'Bütün kâinatı idare eden, onların işlerini yoluna koyan.', meaningEn: 'The Patron.' },
  { id: 78, nameAr: 'الْمُتَعَالِي', nameTr: 'El-Müteâlî', meaning: 'Son derece yüce olan.', meaningEn: 'The Supremly Exalted.' },
  { id: 79, nameAr: 'الْبَرِّ', nameTr: 'El-Berr', meaning: 'İyilik ve ihsanı bol, iyilik ve ihsan kaynağı.', meaningEn: 'The Good.' },
  { id: 80, nameAr: 'التَّوَّابِ', nameTr: 'Et-Tevvâb', meaning: 'Tövbeleri kabul edip, günahları bağışlayan.', meaningEn: 'The Ever-Returning.' },
  { id: 81, nameAr: 'الْمُنْتَقِمِ', nameTr: 'El-Müntakim', meaning: 'Zalimlerin cezasını veren, intikam alan.', meaningEn: 'The Avenger.' },
  { id: 82, nameAr: 'الْعَفُوِّ', nameTr: 'El-Afüvv', meaning: 'Affı çok olan, günahları affeden.', meaningEn: 'The Pardoner.' },
  { id: 83, nameAr: 'الرَّءُوفِ', nameTr: 'Er-Raûf', meaning: 'Çok merhametli, pek şefkatli.', meaningEn: 'The Kind.' },
  { id: 84, nameAr: 'مَالِكِ الْمُلْكِ', nameTr: 'Mâlik-ül Mülk', meaning: 'Mülkün, her varlığın asıl sahibi.', meaningEn: 'The Ruler of the Kingdom.' },
  { id: 85, nameAr: 'ذُو الْجَلَالِ وَالْإِكْرَامِ', nameTr: 'Zül-Celâli vel İkrâm', meaning: 'Celal, azamet ve pek büyük ikram sahibi.', meaningEn: 'The Lord of Majesty and Bounty.' },
  { id: 86, nameAr: 'الْمُقْسِطِ', nameTr: 'El-Muksit', meaning: 'Bütün işleri denk ve birbirine uygun yapan.', meaningEn: 'The Equitable One.' },
  { id: 87, nameAr: 'الْجَامِعِ', nameTr: 'El-Câmi', meaning: 'Mahşerde her mahlukatı bir araya toplayan.', meaningEn: 'The Gatherer.' },
  { id: 88, nameAr: 'الْغَنِيِّ', nameTr: 'El-Ganiyy', meaning: 'Her türlü zenginlik sahibi, ihtiyacı olmayan.', meaningEn: 'The Rich One.' },
  { id: 89, nameAr: 'الْمُغْنِي', nameTr: 'El-Muğnî', meaning: 'Müstağni kılan. İhtiyaç gideren, zengin eden.', meaningEn: 'The Enricher.' },
  { id: 90, nameAr: 'الْمَانِعِ', nameTr: 'El-Mâni', meaning: 'Dilemediği şeye mani olan, engelleyen.', meaningEn: 'The Preventer of Harm.' },
  { id: 91, nameAr: 'الضَّارِّ', nameTr: 'Ed-Dârr', meaning: 'Elem, zarar verenleri yaratan.', meaningEn: 'The Creator of the Harmful.' },
  { id: 92, nameAr: 'النَّافِعِ', nameTr: 'En-Nâfi', meaning: 'Fayda veren şeyleri yaratan.', meaningEn: 'The Creator of Good.' },
  { id: 93, nameAr: 'النُّورِ', nameTr: 'En-Nûr', meaning: 'Âlemleri nurlandıran, dilediğine nur veren.', meaningEn: 'The Light.' },
  { id: 94, nameAr: 'الْهَادِي', nameTr: 'El-Hâdî', meaning: 'Hidayet veren.', meaningEn: 'The Guide.' },
  { id: 95, nameAr: 'الْبَدِيعِ', nameTr: 'El-Bedî', meaning: 'Eşi ve benzeri olmayan güzellik sahibi, eşsiz yaratan.', meaningEn: 'The Incomparable.' },
  { id: 96, nameAr: 'الْبَاقِي', nameTr: 'El-Bâkî', meaning: 'Varlığının sonu olmayan, ebedi olan.', meaningEn: 'The Everlasting.' },
  { id: 97, nameAr: 'الْوَارِثِ', nameTr: 'El-Vâris', meaning: 'Her şeyin asıl sahibi olan.', meaningEn: 'The Ultimate Inheritor.' },
  { id: 98, nameAr: 'الرَّشِيدِ', nameTr: 'Er-Reşîd', meaning: 'İrşada muhtaç olmayan, doğru yolu gösteren.', meaningEn: 'The Righteous Teacher.' },
  { id: 99, nameAr: 'الصَّبُورِ', nameTr: 'Es-Sabûr', meaning: 'Cezada acele etmeyen, çok sabırlı olan.', meaningEn: 'The Patient One.' }
];
