name: Build iOS with EAS

on:
  push:
    branches:
      - main
  workflow_dispatch: # Bu sayede GitHub üzerinden manuel olarak da tetiklenebilir

jobs:
  build:
    name: Build iOS App
    runs-on: ubuntu-latest # Eğer doğrudan GitHub'ın Mac sunucularında derlemek istersen "macos-latest" yapabilir ve komuta --local ekleyebilirsin
    steps:
      - name: Check for REPOSITORY
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Build iOS App
        run: eas build --platform ios --profile preview --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          EAS_NO_VCS: 1
